---
port_profiles:
  TENANT_A_HYPERVISOR:
    mode: trunk
    vlans: "10,20,100,150"


servers:
  host1:
    adapters:
      - type: nic
        endpoint_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [leaf1, leaf2]
        profile: TENANT_A_HYPERVISOR
        port_channel:
          mode: active
          description: PortChannel
  host2:
    adapters:
      - type: nic
        endpoint_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [leaf3, leaf4]
        profile: TENANT_A_HYPERVISOR
        port_channel:
          mode: active
          description: PortChannel
