---
DC1:
  children:
    CVP:
      hosts:
        ATD_CVP:
          ansible_host: 192.168.0.5
          ansible_httpapi_host: 192.168.0.5
    DC1_FABRIC:
      children:
        DC1_SPINES:
          vars:
            type: spine
          hosts:
            spine1:
              ansible_host: 192.168.0.10
            spine2:
              ansible_host: 192.168.0.11
        DC1_L3LEAFS:
          vars:
            type: l3leaf
          children:
            DC1_LEAF1:
              hosts:
                leaf1:
                  ansible_host: 192.168.0.12
                leaf2:
                  ansible_host: 192.168.0.13
            DC1_LEAF2:
              hosts:
                leaf3:
                  ansible_host: 192.168.0.14
                leaf4:
                  ansible_host: 192.168.0.15
    DC1_TENANT_NETWORKS:
      children:
        DC1_L3LEAFS:
    DC1_SERVERS:
      children:
        DC1_L3LEAFS:
  vars:
    ansible_user: arista
    ansible_password: aristaz2em
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false