---

- name: Configure deployment with CVP
  hosts: ATD_CVP
  connection: local
  gather_facts: false

  tasks:

    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        state: present
        cv_collection: v3
        fabric_name: DC1_FABRIC
        execute_tasks: false